apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: falco
spec:
  destination:
    namespace: falco
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://falcosecurity.github.io/charts
    chart: falco
    targetRevision: 3.6.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
