apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-cluster-apps
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    repoURL: 'https://gitlab.com/your-org/k8s-bootstrap.git'
    path: base
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true