apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-cluster-apps
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/charlmex/k8s-bootstrap.git
    targetRevision: master
    path: base
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

