  GNU nano 6.2                                                                                      trivy.yaml *
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/charlmex/k8s-bootstrap.git
    targetRevision: master
    path: base/monitoring/grafana
    helm:
      valuesFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
