apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
spec:
  destination:
    namespace: security
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/charlmex/k8s-bootstrap.git
    targetRevision: master
    path: base/security/kyverno
    helm:
      valuesFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
