apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
spec:
  destination:
    namespace: kyverno
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/charlmex/k8s-bootstrap.git
    targetRevision: master
    path: base/security/kyverno
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
