apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
spec:
  destination:
    namespace: longhorn-system
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/charlmex/k8s-bootstrap.git
    targetRevision: master
    path: apps/longhorn
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
