apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-ingressroutes
spec:
  project: default
  source:
    repoURL: https://github.com/charlmex/k8s-bootstrap.git
    targetRevision: master
    path: base/networking/traefik-ingressroutes
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
