apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
spec:
  destination:
    namespace: security
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/charlmex/k8s-bootstrap.git
    targetRevision: master
    path: base/vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
