apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
spec:
  destination:
    namespace: traefik
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://helm.traefik.io/traefik
    chart: traefik
    targetRevision: 26.1.0  # Check latest if needed
    helm:
      values: |
        ingressRoute:
          dashboard:
            enabled: true
        ports:
          web:
            exposedPort: 80
          websecure:
            exposedPort: 443
        service:
          type: NodePort  # Or LoadBalancer if your env supports it
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
