apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: falco
  namespace: falco
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`falco.local`)
      kind: Rule
      services:
        - name: falcosidekick-ui
          port: 2802
