apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: trivy
  namespace: monitoring
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`trivy.local`)
      kind: Rule
      services:
        - name: trivy-operator
          port: 80
