apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: vault
  namespace: security
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`vault.local`)
      kind: Rule
      services:
        - name: vault
          port: 8200
