prometheus:
  prometheusSpec:
    securityContext:
      runAsUser: 65534
      runAsGroup: 65534
      fsGroup: 65534
    podSecurityContext:
      fsGroup: 65534
    # Disable persistent storage
    storageSpec: {}
    # OR explicitly disable with:
    # storageSpec:
    #   emptyDir: {}
